### ISSUE TITLE
Move Docs content to Github Wiki and add a Roadmap to it

### ISSUE THREAD

**Issue by chespinoza** [thingful/device-hub#48]
We are not using wiki feature, we could move the documentation there in order to have an ordered space to display it, also we could add a Roadmap.

**Comment by chespinoza** [comment]
Also, we have to add more documentation and examples for the available commands in the CLI.

**Comment by mdevilliers** [comment]
One key concern for not using the wiki for documentation as changes aren't subject to a Pull Request -> Review -> Merge workflow. Keeping the documentation as part of the repo e.g. docs folder _should_ also keep the docs in sync with the code.

I am in favor of a road map going on the Wiki.

**Comment by chespinoza** [comment]
@mdevilliers What do you think about adding to the wiki an index(Home) doc with ordered links to the documentation in the docs folder? even the roadmap could be in the docs folder but be mentioned in the wiki home.

**Comment by mdevilliers** [comment]
Sounds like a good, pragmatic solution.

**Comment by chespinoza** [comment]
Great, let's crack on it. ;)

**Comment by chespinoza** [comment]
Related to PR#59
