### ISSUE TITLE
Batching, compression and loadshedding for endpoints 

### ISSUE THREAD

**Issue by mdevilliers** [thingful/device-hub#74]
The endpoints functionality is naive to say the least.

It would be useful when creating a pipe to be able to
- specify a batching parameter e.g. forward every n requests - this should default to 1
- specify a compression parameter e.g. the contents of the endpoint request (which might contain many measurements) should be zipped. This should default to false.
- specify a loadshedding parameter e.g. in the case of either a slow performing endpoint or bad network connectivity only keep the last n results or never dropping a message. This should default to 1000 messages. Messages are to be initially held in memory.

I think there is a lot in this ticket however I think that we should be able to put in a system where for each of these algorithms there is either a simple implementation which we will expand on.

**Comment by chespinoza** [comment]
Addressed as 3 different issues: #101 #102 #103
