### ISSUE TITLE
Weird listener behaviors

### ISSUE THREAD

**Issue by chespinoza** [thingful/device-hub#94]
There are some weird behaviors with the mqtt listener, the first seems to be listener implementation and the second could be managed in the registry/cli:

**Case 1: Mqtt Listener connection is persisted after the process is stopped:**

Steps:

1 `./device-hub-cli create -d ../../../examples/config/`
2 start mqtt broker
3 `./device-hub-cli start -e=stdout-endpoint -l=mqtt-listener-local-port-1883 -u=/my-mqtt-uri thingful/device-2`
4 ./device-hub-cli stop /my-mqtt-uri
Result: Connection isn't dropped and remains active (even trying to reconnect) unless the server is restarted.

**Case 2: If the broker isn't online at the process creation moment, the cli throws an error but the process is registered, if the broker is online again the connection isn't stablished, if the server is restarted the process doesn't persist.** 

Steps:
1 `./device-hub-cli create -d ../../../examples/config/`
2 interrupt mqtt broker
3 `./device-hub-cli start -e=stdout-endpoint -l=mqtt-listener-local-port-1883 -u=/my-mqtt-uri thingful/device-2`
4 start mqtt broker
Result: The listener connection doesn't start even with the process being registered.

**Comment by mdevilliers** [comment]
I'll pick these up. All seem pretty straightforward to resolve.
